#dist: trusty
language: node_js
node_js:
  - "12"
sudo: required
services:
  - docker

jobs:
  include:
    - stage:
      before_scripts:
        - cd my-portfolio
        - npm install
      script:
        - npm test
      after_success:
        - echo "Test Success!"
    - stage: Docker build Stage
      script: 
        - cd my-portfolio
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build -t myportfolio .
        - docker images
        - docker tag myportfolio $DOCKER_USERNAME/myportfolio:$TRAVIS_BUILD_NUMBER
        - docker push $DOCKER_USERNAME/myportfolio:$TRAVIS_BUILD_NUMBER
        - docker tag myportfolio $DOCKER_USERNAME/myportfolio
        - docker push $DOCKER_USERNAME/myportfolio:latest